Fns queries migration to use store queries for FNS
fetchai/fetch-wallet pull request #317
Opened 2023-08-22 05:56 UTC by jas2212

2023-08-22 06:38 UTC, sh-wallet commented on packages/fetch-extension/src/pages/fetch-name-service/domain-details/index.tsx
> +    case "mint":
can we make it enum instead of hardcode?

2023-08-23 05:41 UTC, agent-dominatrix requested changes

2023-08-23 05:41 UTC, agent-dominatrix commented on packages/stores/src/query/fns/domain-data.ts
> +    return this.response.data.domain_data;
Avoid "any" typings. Also data can be undefined, so handle that as well.

2023-08-23 05:41 UTC, agent-dominatrix commented on packages/stores/src/query/fns/domain-price.ts
> +}
Avoid "any" typings. Also data and result can be undefined, so handle that as well.

2023-08-23 05:41 UTC, agent-dominatrix commented on packages/stores/src/query/fns/domain-status.ts
> +}
Avoid "any" typings. Also data, domain_status, owned can be undefined, so handle that as well.

2023-08-23 05:41 UTC, agent-dominatrix commented on packages/stores/src/query/fns/primary-domain.ts
> +  }
data can be undefined, so handle that.

2023-09-07 06:18 UTC, agent-dominatrix approved these changes

2023-09-07 13:35 UTC, merged