chore: support bls keys (ECO-1241)
fetchai/fetch-wallet pull request #35
Opened 2022-05-03 12:37 UTC by bryanchriswhite

### Changes

- adds keyring tests for secp256k1 curve keys
- adds `KeyCurve` type
- adds `curve` field on `Keystore` interface
- adds blst-ts dependency for bls12381 support

2022-06-16 14:37 UTC, ejfitzgerald approved these changes

2022-06-16 14:38 UTC, ejfitzgerald requested changes
Whoops approved the wrong one - let me have a look through this one if it is ready

2022-06-16 17:06 UTC, bryanchriswhite commented
CI is failing because [downloadReleaseAsset](https://github.com/fetchai/blst-ts/pull/2/files#diff-a1637bd6fc09124d02c51ea035233114d87388a2905e00a20e1e8290f57fe9d6L6) was trying to download a version that doesn't exist from the origin repo. [blst-ts#2](https://github.com/fetchai/blst-ts/pull/2/files#diff-a1637bd6fc09124d02c51ea035233114d87388a2905e00a20e1e8290f57fe9d6L6) should fix this.

2022-06-20 09:42 UTC, ejfitzgerald approved these changes
Nice!

2022-06-20 10:54 UTC, merged